comments/urls.py
from django.urls import path
from .views import CommentView, CommentDataView

app_name = "comments"

urlpatterns = [
    path('', CommentView.as_view(), name="comment"), 
    path('view', CommentDataView.as_view(), name="comment_data"), 
]

djangocrudAjax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("comments/",include('comments.urls')),
    path("tasks/",include('tasks.urls')),
    path("products/",include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import TaskView, ViewTaskView, TaskDeleteView
app_name = "tasks"

urlpatterns = [
    path('', TaskView.as_view(), name="task"), 
    path('view', ViewTaskView.as_view(), name="view"), 
    path('view/<int:pk>', TaskDeleteView.as_view(), name="delete"), 
    # path('update/<int:pk>', TaskUpdateView.as_view(), name="update"),
]

comments/models.py
from django.db import models

class Comment(models.Model):
    name = models.CharField("name", max_length=50 )
    comment = models.TextField(help_text='digite seu comentario', max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        
        
    def __str__(self):
        return self.name

comments/forms.py
from django import forms
from comments.models import Comment

class CommentForm(forms.ModelForm):
        
    class Meta:
        model = Comment
        fields = ["name","comment"]

comments/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.views import View
from comments.forms import CommentForm
from comments.models import Comment

class CommentView(View):
    form_class = CommentForm
    def get(self, request, *args, **kwargs):
        return render(request, "comments/index.html", {})

    # def get_context_data(self, **kwargs):
    #     context = super(CommentView, self).get_context_data(**kwargs)
    #     context['formset'] = self.get_formset()

    #     return context

    def post(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                # form = self.form_class()
                return JsonResponse({'message': 'success'})
            return JsonResponse({'message': 'Field couldn\'t validate'}) 
        return JsonResponse({'message': 'Wrong request'})

class CommentDataView(View):
    def get(self, request, *args, **kwargs):
        template = loader.get_template("comments/view.html")
        comments = Comment.objects.all()
        context = {
            "comment_list": comments
        }
        return HttpResponse(template.render(context, self.request))

comments/templates/comments/index.html
{% extends 'tasks/layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3">
            
            <form id="formComment" action="{% url 'comments:comment'  %}" autocomplete="off">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <div class="form-group validate">
                            
                                <label class="form-label" for="id_nome">Nome</label>
                                <input type="text" name="name" maxlength="100" class="form-control" placeholder="Nome" title="" required="" id="clear">
                            
                            <label for="comment">Comentários</label>
                            <textarea rows="5" id="clear2" name="comment" class="form-control" placeholder="Digite seu Comentario"></textarea>
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    <div class="col-6">
                        <button type="submit" class="btn btn-primary pl-5 pr-5 btnSave">Save</button>
                    </div>
                </div>
            </form>

            <div class="comment-content mt-5" data-url="{% url 'comments:comment_data' %}">

            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>

    function getComments(){
        $.ajax({
            url: $(".comment-content").data('url'),
            type: "GET",
            success: function(resp){
                $(".comment-content").html(resp);
                document.getElementById('clear2').value=''; 
                document.getElementById('clear').value=''; 
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    }
    getComments();

    $("#formComment").on("submit", function(e){
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this);
        var valid = true;
        $('#formComment textarea').each(function() {
            let $this = $(this);
            
            if(!$this.val()) {
                valid = false;
                $this.parents('.validate').find('.mySpan').text('The '+$this.attr('name').replace(/[\_]+/g, ' ')+' field is required');
            }
        });
    
        if(valid){
            $(".btnSave").text('Saving....').attr('disabled',true);
            let data = $this.serialize();
            //ajax
            $.ajax({
                url: $this.attr('action'),
                type: "POST",
                data: data,
                dataType: 'json',
                success: function(resp){
                    if(resp.message === 'success'){
                        getComments();
                    }else{
                        alert(resp.message);
                    }

                    $(".btnSave").text('Save').attr('disabled',false);
                },
                error: function(resp){
                    console.log('something went wrong');
                    $(".btnSave").text('Save').attr('disabled',false);
                }
            });
        }
        return false;
    });

</script>
{% endblock scripts %}

comments/templates/comments/view.html
<div>
    {% for comment in comment_list %}
    <h5>{{comment.name}}</h5>
        <p>{{ comment.comment }}</p>
        <hr>
    {% endfor %}
</div>