djangocrudAjax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("comments/",include('comments.urls')),
    path("tasks/",include('tasks.urls')),
    path("products/",include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import ProductView, ProductCategoryView

app_name = "products"

urlpatterns = [
    path('', ProductView.as_view(), name="products"), 
    path('<str:category>', ProductCategoryView.as_view(), name="products_category"), 
]

tasks/urls.py
from django.urls import path
from .views import TaskView, ViewTaskView, TaskDeleteView
app_name = "tasks"

urlpatterns = [
    path('', TaskView.as_view(), name="task"), 
    path('view', ViewTaskView.as_view(), name="view"), 
    path('view/<int:pk>', TaskDeleteView.as_view(), name="delete"), 
    # path('update/<int:pk>', TaskUpdateView.as_view(), name="update"),
]

tasks/models.py
from django.db import models

class Task(models.Model):
    owner = models.CharField(max_length = 150)
    name = models.CharField(max_length = 150)
    task_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    
    

tasks/forms.py
from django import forms
from tasks.models import Task

class TaskForm(forms.ModelForm):
        
    class Meta:
        model = Task
        fields = ["owner", "name", "task_date", "start_time", "end_time"]

tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from tasks.forms import TaskForm
from tasks.models import Task
# from django.shortcuts import render, redirect
# from django.template import loader


class TaskView(View):
    form_class = TaskForm

    def post(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                return JsonResponse({"message": "success"})
            return JsonResponse({"message": "Validation failed"})
        return JsonResponse({"message": "Wrong request"})

    def get(self,request, *args, **kwargs):
        return render(request, "tasks/index.html", {})

class ViewTaskView(View):

    def get(self,request, *args, **kwargs):
        tasks = Task.objects.all()
        return render(request, "tasks/view.html", {"tasks":tasks})

class TaskDeleteView(View):
    form_class = TaskForm
    
    def get(self,request, pk, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            task = Task.objects.get(pk=pk)
            task.delete()
            return JsonResponse({"message":"success"})
        return JsonResponse({"message": "ajax failed"})
    
    def post(self, request, pk, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            task = Task.objects.get(pk=pk)
            data = {
                "owner":task.owner,
                "name":task.name,
                "task_date":task.task_date,
                "start_time":task.start_time,
                "end_time":task.end_time
            }
            
            form = self.form_class(request.POST, initial=data)
            if form.is_valid():
                owner = form.cleaned_data['owner']
                name = form.cleaned_data['name']
                task_date = form.cleaned_data['task_date']
                start_time = form.cleaned_data['start_time']
                end_time = form.cleaned_data['end_time']
                
                if form.has_changed():
                    task.owner = owner
                    task.name = name
                    task.task_date = task_date
                    task.start_time = start_time
                    task.end_time = end_time
                    task.save()
                    return JsonResponse({'message': 'success'})
                return JsonResponse({'message': 'dados não editados'})
            
            return JsonResponse({'message': 'dados invalidos'})
        return JsonResponse({'message': 'ajax failed'})



# class TaskUpdateView(View):
#     form_class = TaskForm
    
#     def post(self, request, pk, *args, **kwargs):
#         if request.headers.get('x-requested-with') == 'XMLHttpRequest':
#             task = Task.objects.get(pk-pk)
#             form = self.form_class(request.POST)
#             if form.is_valid():
#                 owner = form.cleaned_data['owner']
#                 name = form.cleaned_data['name']
#                 task_date = form.cleaned_data['task_date']
#                 strat_time = form.cleaned_data['strat_time']
#                 end_time = form.cleaned_data['end_time']
                
#                 task.owner = owner
#                 task.name = name
#                 task.task_date = task_date
#                 task.strat_time = strat_time
#                 task.end_time = end_time
#                 return JsonResponse({'message': 'success'})
#             return JsonResponse({'message': 'dados invalidos'})
#         return JsonResponse({'message': 'ajax failed'})
                
                        
        
    

tasks/templates/tasks/data.html
<table class="table">
    <thead>
        <tr>
            <th>Good</th>
            <th>Bad</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Yes</td>
            <td>No</td>
        </tr>
    </tbody>
</table>

tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3">
            
            <form id="formTask" action="{% url 'tasks:task'  %}" autocomplete="off">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <div class="form-group validate">
                            <label for="owner">Nome</label>
                            <input type="text" name="owner" class="form-control" id="owner" placeholder="nome">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                        <div class="form-group validate">
                            <label for="name"> Tarefa</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Tarefa">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                        <div class="form-group validate">
                            <label for="task_date">data</label>
                            <input type="date" name="task_date" class="form-control" id="Data">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group validate">
                            <label for="start_time">Começo</label>
                            <input type="time" name="start_time" class="form-control" id="Começo">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group validate">
                            <label for="end_time">Fim</label>
                            <input type="time" name="end_time" class="form-control" id="Fim">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>
                    <div class="col-6">
                        <button type="submit" class="btn btn-primary pl-5 pr-5 btnSave">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $("#formTask").on("submit", function(e){
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this);
        var valid = true;
        $('#formTask input').each(function() {
            let $this = $(this);
            
            if(!$this.val()) {
                valid = false;
                $this.parents('.validate').find('.mySpan').text('The '+$this.attr('name').replace(/[\_]+/g, ' ')+' field is required');
            }
        });
    
        if(valid){
            $(".btnSave").text('Saving....').attr('disabled',true);
            let data = $this.serialize();
            $.ajax({
                url: $this.attr("action"),
                type: "POST",
                data: data,
                dataType: "json",
                success: function(resp){
                    if(resp.message == "success"){
                        alert("Item Salvo");
                        $("#formTask")[0].reset();
                    }
                    else{
                        alert(resp.message);
                    }
                    $(".btnSave").text('Save').attr('disabled',false);
                },
                error: function(resp){
                    console.log("Something went wrong");
                    $(".btnSave").text('Save').attr('disabled',false);
                }
            });
        }
        return false;
    });
</script>
{% endblock scripts %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Tasky</title>
  {% load static %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  {% block styles %}
  {% endblock styles %}
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <a class="navbar-brand" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto ml-5">

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'tasks:task'  %}">Add Tarefas <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:view'  %}">Tarefas</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar ">
      <a class="navbar-brand" href="{% url 'products:products'  %}">Produtos</a>
    </nav>


  </div>

  <!-- Content Wrapper. Contains page content -->
  {% block content %}
  {% endblock content %}
  <!-- /.content-wrapper -->



  {% comment %}
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    crossorigin="anonymous"></script> {% endcomment %}
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
  {% block scripts %}
  {% endblock scripts %}
</body>

</html>

tasks/templates/tasks/tutorial.html
{% extends 'tasks/layout.html' %}

{% block styles %}
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-12 text-center">
            <button class="btn btn-primary btn-get-data">Get HTML file in a div</button>
            <div class="content-data mt-4" data-url="{% url 'tasks:tutorial_data' %}">File content will display here</div>
        </div>
    </div>
</div>



{% endblock content %}

{% block scripts %}
<script>
    $(".btn-get-data").on("click", function(){
        $.ajax({
            url: $(".content-data").data('url'),
            type: "GET",
            success: function(resp){
                $(".content-data").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    });
</script>
{% endblock scripts %}

tasks/templates/tasks/view.html
{% extends 'tasks/layout.html' %}

{% block styles %}
<style>
    .text-red {
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-12">
            <table class="table" id="table">
                <thead>
                    <tr>
                        <th scope="col">pessoa</th>
                        <th scope="col">Tarefa</th>
                        <th scope="col">Data</th>
                        <th scope="col">Começo</th>
                        <th scope="col">Fim</th>
                        <th scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr class="record">
                        <td>{{ task.owner }}</td>
                        <td>{{ task.name }}</td>
                        <td>{{ task.task_date }}</td>
                        <td>{{ task.start_time }}</td>
                        <td>{{ task.end_time }}</td>
                        <td>
                            <a href="{% url 'tasks:delete' task.id  %}" data-date="{{ task.task_date|date:'Y-m-d' }}"
                                data-start="{{ task.start_time|date:'H:i' }}" data-end="{{ task.end_time|date:'H:i' }}"
                                class="link-edit mr-2 text-primary">edit</a>
                            <a href="{% url 'tasks:delete' task.id  %}" class="link-delete text-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formEdit" action="">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group validate">
                        <input type="text" name="owner" class="form-control" placeholder="Enter owner name">
                        <small class="text-red text-muted mySpan"></small>
                    </div>
                    <div class="form-group validate">
                        <input type="text" name="name" class="form-control" placeholder="Enter owner name">
                        <small class="text-red text-muted mySpan"></small>
                    </div>
                    <div class="form-group validate">
                        <input type="date" name="task_date" class="form-control" placeholder="Enter owner name">
                        <small class="text-red text-muted mySpan"></small>
                    </div>
                    <div class="form-group validate">
                        <input type="time" name="start_time" class="form-control" placeholder="Enter owner name">
                        <small class="text-red text-muted mySpan"></small>
                    </div>
                    <div class="form-group validate">
                        <input type="time" name="end_time" class="form-control" placeholder="Enter owner name">
                        <small class="text-red text-muted mySpan"></small>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btnUpdate">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}

<script>
    $("#table tbody").on("click", ".link-edit", function (e) {
        e.preventDefault();
        var $this = $(this);
        let owner = $this.parents(".record").find('td').eq(0).text();
        let task = $this.parents(".record").find('td').eq(1).text();

        let taskDate = $this.data('date')
        let startTime = $this.data('start')
        let endTime = $this.data('end')

        <!-- tipo da variavel -->
        console.log(typeof task);
        console.log(typeof endTime);

        $("#formEdit input[name='owner']").val(owner);
        $("#formEdit input[name='name']").val(task);
        $("#formEdit input[name='task_date']").val(taskDate);
        $("#formEdit input[name='start_time']").val(startTime);
        $("#formEdit input[name='end_time']").val(endTime);
        $("#formEdit").attr("action", $this.attr('href'));

        $("#editModal").modal("show");
        return false;
    })

    $("#formEdit").on("submit", function (e) {
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this);
        var valid = true;
        $('#formEdit input').each(function () {
            let $this = $(this);

            if (!$this.val()) {
                valid = false;
                $this.parents('.validate').find('.mySpan').text('the ' + $this.attr('name').replace(/[\_]+/g, ' ') + ' field is required')
            };
        });
        if (valid) {
            let data = $this.serialize();
            $.ajax({
                url: $this.attr("action"),
                type: "POST",
                data: data,
                dataType: "json",
                success: function (resp) {

                    if (resp.message === "success") {
                        alert("item atualizado");
                        $("#editModal").modal('hide');
                    }
                    else {
                        alert(resp.message);
                    }
                },
                error: function (resp) {
                    console.log("something went wrong");
                }
            });

        }
        return false;

    })

    $(".link-delete").on("click", function (e) {
        e.preventDefault();
        var $this = $(this);
        if (confirm("confirme o delete.")) {
            $.ajax({
                url: $this.attr("href"),
                type: "GET",
                dataType: "json",
                success: function (resp) {
                    if (resp.message == "success") {
                        $this.parents(".record").fadeOut("slow", function () {
                            $this.parents(".record").remove();
                        });
                    } else {
                        alert(resp.message);
                    }
                },

            });
        }
        return false;
    });
</script>

{% endblock scripts %}