djangocrudAjax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("comments/",include('comments.urls')),
    path("tasks/",include('tasks.urls')),
    path("products/",include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import ProductView, ProductCategoryView

app_name = "products"

urlpatterns = [
    path('', ProductView.as_view(), name="products"), 
    path('<str:category>', ProductCategoryView.as_view(), name="products_category"), 
]

tasks/urls.py
from django.urls import path
from .views import TaskView, ViewTaskView, TaskDeleteView
app_name = "tasks"

urlpatterns = [
    path('', TaskView.as_view(), name="task"), 
    path('view', ViewTaskView.as_view(), name="view"), 
    path('view/<int:pk>', TaskDeleteView.as_view(), name="delete"), 
    # path('update/<int:pk>', TaskUpdateView.as_view(), name="update"),
]

products/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length = 150)
    category = models.CharField(max_length=50)
    image = models.ImageField(upload_to="products")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.name}"
    
    

products/forms.py
from django import forms
from products.models import Product

class ProductForm(forms.ModelForm):
        
    class Meta:
        model = Product
        fields = ["name", "category", "image"]

products/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.shortcuts import render, redirect
from django.template import loader
from products.models import Product



class ProductView(View):
    def get(self,request, *args, **kwargs):
        products = Product.objects.values('category').distinct()
        context = {
            "product_list": products
        }
        return render(request, "products/index.html", context)

class ProductCategoryView(View):
    def get(self,request, category, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            products = Product.objects.filter(category=category)
            context = {
                "product_image_list": products
            }
            template = loader.get_template("products/category.html")
            return HttpResponse(template.render(context, self.request))
        return HttpResponse("Wrong request")

products/templates/products/category.html
<div class="row">
    {% for product in product_image_list %}
    <div class="col-sm-4">
        <img src="{{product.image.url}}" alt="image" width="200" height="200" class="img-responsive">
    </div>
    {% endfor %}
</div>

products/templates/products/index.html
{% extends 'tasks/layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                {% for product in product_list %}
                
                <li class="nav-item" role="presentation">
                    <a class="nav-link {% if forloop.counter == 1 %} active {% endif %} category-link" id="{{product.category}}-tab" data-url="{% url 'products:products_category' product.category  %}" data-toggle="tab" href="#{{product.category}}" role="tab" aria-controls="home" aria-selected="true">{{product.category|upper}}</a>
                  </li>
                {% endfor %}
                
                <!-- <li class="nav-item" role="presentation">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Category</a>
                </li>
                <li class="nav-item" role="presentation">
                  <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Category</a>
                </li> -->
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="mt-4 imageContent">

                </div>
            </div>
            
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    function getFirstCategoryImages()
    {
        let url  = $(".category-link:first").data('url');
        $.ajax({
            url: url,
            type: "GET",
            success: function(resp){
                $(".imageContent").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    }

    getFirstCategoryImages();

    $(".category-link").on("click", function(){
        var $this = $(this);
        $.ajax({
            url: $this.data('url'),
            type: "GET",
            success: function(resp){
                $(".imageContent").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
        return false;
    });
</script>
{% endblock scripts %}